musuimsa:
  shelter:
    api:
      base-url: "https://www.safetydata.go.kr"
      path: "/V2/api/DSSP-IF-10942"
      service-key: "${SHELTER_SERVICE_KEY}"
      page-size: 500
      format: "json"
      timeout-ms: 10000

proxy:
  enabled: false
